### ISSUE TITLE
Add toast message component

### ISSUE THREAD

**Issue by jpatrici** [chingu-voyages/v39-bears-team-16#118]
- Add toast message to show error in the page using https://www.npmjs.com/package/react-toastify

**Comment by akinsanmi60** [comment]
I need more info in starting this app... I got this error while starting with npm start.
![Modal styled tsx - v39-bears-team-16 - Visual Studio Code 7_13_2022 3_40_21 PM (2)](https://user-images.githubusercontent.com/90307436/178762637-cf255c58-228c-46f1-9ea4-f196c44932ff.png)

**Comment by RDiMag** [comment]
@jpatrici I think this is done, can it be closed?
