### ISSUE TITLE
Setup routers

### ISSUE THREAD

**Issue by Danneytrieu** [chingu-voyages/v39-bears-team-16#12]

**Comment by Danneytrieu** [comment]
- homepage
- signup
- login
- admin/dashboard
- admin/manage
- student/dashboard
- student/manage

**Comment by jpatrici** [comment]
proposing these as the routes:
Add these basic routes:

- `/` and `/home` for the homepage after login. This should be the default route
*Note*: in the future, the route can be divided even further by doing `/admin/dashboard` and `/student/dashboard`
- `/sign-up`
- `/sign-in`
- `/forgot-password`

Optional: (can be added later)
- `/admin` and `/student`
    - `/class`
    - `/class/:id`
