### ISSUE TITLE
Copyedit/Proofread of Content

### ISSUE THREAD

**Issue by RDiMag** [chingu-voyages/v39-bears-team-16#43]
Copyedit/proofread all copy within Figma.

I can do this again for the copy on each page as it is built.

**Comment by RDiMag** [comment]
@Danneytrieu @jpatrici @theodorusandi I have reviewed and made some changes and a couple suggested changes in comments.

**Comment by jpatrici** [comment]
will close this issue for now, since this is just for the frontend, and looks like they're done :). thank you! should create another ticket for the backend copy later if needed.
